# 메세지 설정
messages:
  # 접두사
  prefix: "&8[&6기본템&8] &f"

  # 플레이어가 아닐 때
  only_player: "&c해당 명령어는 플레이어만 사용 가능합니다."

  # 잘못된 명령어일 때
  wrong_command: "&c잘못된 명령어입니다."

  # 명령어를 위한 권한이 없을 때
  no_permission: "&c당신은 이 명령어를 사용할 권한이 없습니다."

  # 플레이어가 없을 떄
  no_player: "&c해당 플레이어를 찾을 수 없습니다."


  # 기본템을 지급 받았을 때
  kit_received:

    # 메세지
    message: "&a기본템을 지급 받았습니다."

    # 타이틀
    title:
      enable: true

      title: "&a기본템"
      subtitle: "&f지급완료"
      fadein: 1
      stay: 3
      fadeout: 1

  # 이미 기본템을 지급 받았을 때
  already_received: "&c당신은 이미 기본템을 지급 받았습니다."

  # 인벤토리에 아이템이 있어 기본템을 지급받을 수 없을 때
  inventory_no_space: "&c인벤토리에 공간이 부족해 기본템을 지급받을 수 없습니다."

  # 기본템을 설정했을 때
  kit_set: "&a기본템을 설정했습니다."

  # 기본템을 비어있게 설정했을 때
  kit_cannot_empty: "&c기본템을 비워둘 수 없습니다."

  # 기본템 지급내역을 초기화 했을 때
  # {target}  - 대상 플레이어
  reset: "&a{target}님의 기본템 지급내역을 초기화 했습니다."


  # 콘피그를 리로드 완료했을 때
  reload: "&a콘피그를 리로드 완료했습니다."


# 플러그인 동작 설정
settings:

  # 서버 접속 시, 기본 템을 자동 지급할지 여부
  enable_auto_kit: true


# 기본템 설정
defaultkit:
  size: 36
  title: "기본템 설정 | ST-DefaultKit"
  items:
    '0':
      material: IRON_PICKAXE
      amount: 1
      durability: 0
    '1':
      material: IRON_AXE
      amount: 1
      durability: 0
    '2':
      material: IRON_SWORD
      amount: 1
      durability: 0
    '5':
      material: CHAINMAIL_HELMET
      amount: 1
      durability: 0
    '6':
      material: CHAINMAIL_CHESTPLATE
      amount: 1
      durability: 0
    '7':
      material: CHAINMAIL_LEGGINGS
      amount: 1
      durability: 0
    '8':
      material: CHAINMAIL_BOOTS
      amount: 1
      durability: 0