name: ST-DefaultKit
main: net.starly.defaultkit.DefaultKitMain
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

description: DefaultKit Plugin.

version: 1.3.3
api-version: 1.13

softdepend:
  - ST-Core

commands:
  defaultkit:
    aliases: [ dk, 기본템 ]